[package]
name = "imt"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hex = "0.4.3"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
