[package]
name = "zk-kit-imt"
version = "0.0.4"
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "Incremental Merkle Tree"

[dependencies]
hex = "0.4.3"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
